WHITESPACE = _{ " " | "\t" }

SPECIAL_CHARS = {
    "$"
  | "\""
  | "'"
  | "@"
  | "\\"
  | ">"
  | "<"
  | "2>"
  | "1>"
  | ">>"
  | "2>>"
  | "1>>"
  | "|"
  | "&"
}

regular_part       = @{ (!WHITESPACE ~ !"'" ~ !SPECIAL_CHARS ~ ANY)+ }
escape_char        = @{ "\\" ~ ANY }
word               =  ${ (regular_part | escape_char)+ }

quoted_part        = @{ "'" ~ (!"'" ~ ANY)* ~ "'" }

double_quoted_regular = @{ (!"\"" ~ !"\\" ~ ANY)+ }
double_quoted_escape_interpreted = @{ "\\" ~ ("\"" | "\\" | "$" | "`" | "\n") }
double_quoted_escape_literal = @{ "\\" ~ (!"\n" ~ ANY) }
double_quoted_part = ${ "\"" ~ (double_quoted_regular | double_quoted_escape_interpreted | double_quoted_escape_literal)* ~ "\"" }

segment = { word | quoted_part | double_quoted_part }

arg     = ${ segment+ }
command =  { segment }

write_stdout    = { (">" | "1>") ~ segment }
write_stderr    = { "2>" ~ segment }
override_stdout = { (">>" | "1>>") ~ segment }
override_sterr  = { "2>>" ~ segment }

redirect = { write_stdout | write_stderr | override_stdout | override_sterr }

background = { "&" }

element = _{ redirect | arg }
input = { redirect* ~ command ~ element* }

pipe_sep  = _{ "|" }
pipe = { pipe_sep ~ input}

line = { SOI ~ input ~ pipe* ~ background* ~ EOI }
